import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Autogenerated from the directory structure for every docs instance.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
