#!/usr/bin/env bash
# Lay out two versioned Docusaurus docs instances (pipelines, operator)
# from upstream docs pulled into _src/. Reproducible & throwaway (PoC for #732).
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$PWD"
SRC="$ROOT/_src"

# instance | current-src (main) | "version:src" pairs (newest first)
setup_instance() {
  local id="$1" current_src="$2"; shift 2
  local versions=("$@")

  echo "== instance: $id =="
  rm -rf "$id" "${id}_versioned_docs" "${id}_versioned_sidebars" "${id}_versions.json"

  # current version (= main)
  mkdir -p "$id"
  cp -r "$SRC/$current_src/docs/." "$id/"

  # versioned snapshots
  mkdir -p "${id}_versioned_docs" "${id}_versioned_sidebars"
  local json="["
  local first=1
  for pair in "${versions[@]}"; do
    local v="${pair%%:*}" s="${pair##*:}"
    cp -r "$SRC/$s/docs/." "${id}_versioned_docs/version-$v/"
    # autogenerated sidebar per version
    echo '{"docsSidebar":[{"type":"autogenerated","dirName":"."}]}' \
      > "${id}_versioned_sidebars/version-$v-sidebars.json"
    [ $first -eq 1 ] && first=0 || json+=","
    json+="\"$v\""
  done
  json+="]"
  echo "$json" > "${id}_versions.json"
  echo "  versions.json: $json"
  echo "  current md: $(find "$id" -name '*.md' | wc -l)"
}

setup_instance pipelines pipeline-main "1.12.x:pipeline-v1.12" "1.9.x:pipeline-v1.9"
setup_instance operator operator-main "0.79.x:operator-v0.79" "0.78.x:operator-v0.78"
echo "Done."
